geometry:
  mode: 0D
disk:
  geometry:
    r_in_RM: 1.3
    r_out_RM: 1.3
    r_profile: uniform
    p_index: 0.0
material:
  rho: 3000.0
radiation:
  TM_K: 4000.0
sizes:
  s_min: 1e-07
  s_max: 0.001
  n_bins: 24
initial:
  mass_total: 1e-08
  s0_mode: upper
dynamics:
  e0: 0.05
  i0: 0.01
  t_damp_orbits: 5.0
  f_wake: 1.0
  rng_seed: 9876
  e_mode: fixed
  i_mode: fixed
psd:
  alpha: 1.8
  wavy_strength: 0.05
qstar:
  Qs: 100000.0
  a_s: 0.1
  B: 0.3
  b_g: 1.36
  v_ref_kms:
    - 1.0
    - 2.0
supply:
  mode: const
  const:
    prod_area_rate_kg_m2_s: 1e-05
  mixing:
    epsilon_mix: 1.0
sinks:
  mode: sublimation
  enable_sublimation: true
  enable_gas_drag: false
  T_sub: 1300.0
  sub_params:
    mode: hkl
    psat_model: clausius
    alpha_evap: 0.02
    mu: 0.0440849
    A: 13.613
    B: 17850.0
    eta_instant: 0.2
    dT: 50.0
    P_gas: 0.0
numerics:
  t_end_orbits: 0.25
  t_end_years:
  dt_init: 5.0
  eval_per_step: false
  orbit_rollup: false
io:
  outdir: tmp_debug/combined_mass_balance
  debug_sinks: false
